# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

User.create([
  { :fb_id => "727525843", :access_token => "AAAC89wa9QZBwBACVdxc8SP7otl7VgQWRRfaBUTvigm3iQtLfG6BEVeYYYmu0qaYCmGXdGH00BK5cHUcNtgfgbegtf8UeKNdwswwzqDwZDZD", :scaned => nil, :created_at => "2012-10-24 15:49:26", :updated_at => "2012-10-24 15:49:26", :api_key => "uqn2te1Qf2RiMCDJ8ltesQ" },
  { :fb_id => "100003783250569", :access_token => "AAADN8gDlHY0BAJJPb2KZC3 aBN6rLwZADuwcfIZAokyQUo4PVsKjaojxj4o8v4EVcylg8ZADTUOlkDxAu4tnJApLaxDgKkiAW2R4vZB eHUZAAZDZD", :scaned => nil, :created_at => "2012-10-25 06:22:03", :updated_at => "2012-10-25 06:22:03", :api_key => "7NHbMkUA9dJjW0NPMMnXDA" }
], :without_protection => true )


